apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k8s/aws-roles-anywhere.yaml
  - k8s/argo-workflows-rbac.yaml
  - k8s/hpo-workflow.yaml
  - k8s/inference-api.yaml
  - k8s/triton.yaml
  - k8s/dataset-automation.yaml
  - k8s/training-pipeline.yaml
  - k8s/evaluation-pipeline.yaml
  - k8s/model-promotion.yaml
  - k8s/smoke-test.yaml
  - gitops/production/model-release.yaml
  - gitops/policies/evaluation-policy.yaml
  - gitops/policies/dataset-quality-policy.yaml
