apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-api
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-api
  template:
    metadata:
      labels:
        app: inference-api
    spec:
      containers:
        - name: api
          image: safety-inference-api:1.0.0
          imagePullPolicy: Never
          env:
            - name: TRITON_URL
              value: http://triton.mlops.svc.cluster.local:8000
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: inference-api
  namespace: mlops
spec:
  type: ClusterIP
  selector:
    app: inference-api
  ports:
    - name: http
      port: 8080
      targetPort: http
