apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-api
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-api
  template:
    metadata:
      labels:
        app: inference-api
      annotations:
        safety.mlops/model-version: v1
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
        - name: api
          image: 323974325951.dkr.ecr.ap-northeast-2.amazonaws.com/safety-mlops/inference-api@sha256:e0242473fe9ddb53a7898ee94a505b38366b4f951a41880cb25ecd1a7535dfd7
          imagePullPolicy: IfNotPresent
          env:
            - name: TRITON_URL
              value: http://triton.mlops.svc.cluster.local:8000
            - name: MODEL_VERSION
              valueFrom:
                configMapKeyRef:
                  name: safety-model-release
                  key: MODEL_VERSION
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: inference-api
  namespace: mlops
spec:
  type: ClusterIP
  selector:
    app: inference-api
  ports:
    - name: http
      port: 8080
      targetPort: http
