image:
  repository: 323974325951.dkr.ecr.ap-northeast-2.amazonaws.com/safety-mlops/mlflow
  tag: "sha-a52ceb5d7b12"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-registry

replicaCount: 1

service:
  type: ClusterIP
  port: 5000

persistence:
  storageClass: local-path
  size: 1Gi

s3:
  bucket: ""
  artifactPrefix: artifacts/mlflow

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 1Gi
